version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: postgres:14.2-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data